board:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.50.128
    port: 3306
    database: zzuli_board
    username: root
    password: 123456
  redis:
    host: 192.168.50.128
    port: 6379
    database: 2
    password: 123456
